### ISSUE TITLE
Get request for user which doesn't exist crashes docker image

### ISSUE THREAD

**Issue by gnomaditr0n** [blockapps/issues#3]
* Bloc API
 *  1.1 (I believe, current docker image as of this issue report)
 * Private Instance
 * Ubuntu 14.0.4 LTS trusty
 * Docker version 1.11.2, build b9f10c9

STEPS:
 * Run the deploy script to create a new resource group
 * Do not create any users or do anything at all with the network
 * In a browser, goto `http://<myDeployment>:8000/users/someuser`

EXPECTED:
The server will return a 404

ACTUAL:
The dashboard docker image crashes.  logs show:

/usr/lib/strato/bloc-server/bin/main.js:338
          throw err;
          ^
TypeError: Cannot read property 'pipe' of null
    at /etc/strato/bloc-server/app/routes/users.js:65:7
    at Layer.handle [as handle_request] (/etc/strato/bloc-server/node_modules/express/lib/router/layer.js:95:5)
    at next (/etc/strato/bloc-server/node_modules/express/lib/router/route.js:131:13)
    at cors (/etc/strato/bloc-server/node_modules/cors/lib/index.js:178:7)
    at /etc/strato/bloc-server/node_modules/cors/lib/index.js:228:17
    at originCallback (/etc/strato/bloc-server/node_modules/cors/lib/index.js:217:15)
    at /etc/strato/bloc-server/node_modules/cors/lib/index.js:222:13
    at optionsCallback (/etc/strato/bloc-server/node_modules/cors/lib/index.js:203:9)
    at /etc/strato/bloc-server/node_modules/cors/lib/index.js:208:7
    at Layer.handle [as handle_request] (/etc/strato/bloc-server/node_modules/express/lib/router/layer.js:95:5)
    at next (/etc/strato/bloc-server/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/etc/strato/bloc-server/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/etc/strato/bloc-server/node_modules/express/lib/router/layer.js:95:5)
    at /etc/strato/bloc-server/node_modules/express/lib/router/index.js:277:22
    at param (/etc/strato/bloc-server/node_modules/express/lib/router/index.js:349:14)
    at param (/etc/strato/bloc-server/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/etc/strato/bloc-server/node_modules/express/lib/router/index.js:410:3)
    at next (/etc/strato/bloc-server/node_modules/express/lib/router/index.js:271:10)
    at Function.handle (/etc/strato/bloc-server/node_modules/express/lib/router/index.js:176:3)
    at router (/etc/strato/bloc-server/node_modules/express/lib/router/index.js:46:12)
    at Layer.handle [as handle_request] (/etc/strato/bloc-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/etc/strato/bloc-server/node_modules/express/lib/router/index.js:312:13)

**Comment by kejace** [comment]
Closing this due to upgrade to `1.2`. Let's reopen if issue persist.
